export const AppPaths = {
    HOME: '/',

    SALADS: '/salads',
    SNACKS: '/snacks',
    FIRST_COURSES: '/first-courses',
    MAIN_COURSES: '/main-courses',
    DESSERTS: '/desserts',
    GRILL: '/grill',
    VEGAN: '/vegan',
    KIDS: '/kids',
    MEDICAL: '/medical',
    NATIONAL: '/national',
    SAUCES: '/sauces',
    DRINKS: '/drinks',
    PRESERVES: '/preserves',
    JUICY: '/juicy',

    SALADS_APPETIZERS: '/salads/appetizers',
    SALADS_FIRST_COURSES: '/salads/first-courses',
    SALADS_MAIN_COURSES: '/salads/main-courses',
    SALADS_SIDES: '/salads/sides',
    SALADS_DESSERTS: '/salads/desserts',
    SALADS_BAKING: '/salads/baking',
    SALADS_RAW: '/salads/raw',
    SALADS_DRINKS: '/salads/drinks',

    SNACKS_APPETIZERS: '/snacks/appetizers',
    SNACKS_FIRST_COURSES: '/snacks/first-courses',
    SNACKS_MAIN_COURSES: '/snacks/main-courses',
    SNACKS_SIDES: '/snacks/sides',
    SNACKS_DESSERTS: '/snacks/desserts',
    SNACKS_BAKING: '/snacks/baking',
    SNACKS_RAW: '/snacks/raw',
    SNACKS_DRINKS: '/snacks/drinks',

    FIRST_COURSES_APPETIZERS: '/first-courses/appetizers',
    FIRST_COURSES_FIRST_COURSES: '/first-courses/first-courses',
    FIRST_COURSES_MAIN_COURSES: '/first-courses/main-courses',
    FIRST_COURSES_SIDES: '/first-courses/sides',
    FIRST_COURSES_DESSERTS: '/first-courses/desserts',
    FIRST_COURSES_BAKING: '/first-courses/baking',
    FIRST_COURSES_RAW: '/first-courses/raw',
    FIRST_COURSES_DRINKS: '/first-courses/drinks',

    MAIN_COURSES_APPETIZERS: '/main-courses/appetizers',
    MAIN_COURSES_FIRST_COURSES: '/main-courses/first-courses',
    MAIN_COURSES_MAIN_COURSES: '/main-courses/main-courses',
    MAIN_COURSES_SIDES: '/main-courses/sides',
    MAIN_COURSES_DESSERTS: '/main-courses/desserts',
    MAIN_COURSES_BAKING: '/main-courses/baking',
    MAIN_COURSES_RAW: '/main-courses/raw',
    MAIN_COURSES_DRINKS: '/main-courses/drinks',

    DESSERTS_APPETIZERS: '/desserts/appetizers',
    DESSERTS_FIRST_COURSES: '/desserts/first-courses',
    DESSERTS_MAIN_COURSES: '/desserts/main-courses',
    DESSERTS_SIDES: '/desserts/sides',
    DESSERTS_DESSERTS: '/desserts/desserts',
    DESSERTS_BAKING: '/desserts/baking',
    DESSERTS_RAW: '/desserts/raw',
    DESSERTS_DRINKS: '/desserts/drinks',

    GRILL_APPETIZERS: '/grill/appetizers',
    GRILL_FIRST_COURSES: '/grill/first-courses',
    GRILL_MAIN_COURSES: '/grill/main-courses',
    GRILL_SIDES: '/grill/sides',
    GRILL_DESSERTS: '/grill/desserts',
    GRILL_BAKING: '/grill/baking',
    GRILL_RAW: '/grill/raw',
    GRILL_DRINKS: '/grill/drinks',

    VEGAN_APPETIZERS: '/vegan/appetizers',
    VEGAN_FIRST_COURSES: '/vegan/first-courses',
    VEGAN_MAIN_COURSES: '/vegan/main-courses',
    VEGAN_SIDES: '/vegan/sides',
    VEGAN_DESSERTS: '/vegan/desserts',
    VEGAN_BAKING: '/vegan/baking',
    VEGAN_RAW: '/vegan/raw',
    VEGAN_DRINKS: '/vegan/drinks',

    KIDS_APPETIZERS: '/kids/appetizers',
    KIDS_FIRST_COURSES: '/kids/first-courses',
    KIDS_MAIN_COURSES: '/kids/main-courses',
    KIDS_SIDES: '/kids/sides',
    KIDS_DESSERTS: '/kids/desserts',
    KIDS_BAKING: '/kids/baking',
    KIDS_RAW: '/kids/raw',
    KIDS_DRINKS: '/kids/drinks',

    MEDICAL_APPETIZERS: '/medical/appetizers',
    MEDICAL_FIRST_COURSES: '/medical/first-courses',
    MEDICAL_MAIN_COURSES: '/medical/main-courses',
    MEDICAL_SIDES: '/medical/sides',
    MEDICAL_DESSERTS: '/medical/desserts',
    MEDICAL_BAKING: '/medical/baking',
    MEDICAL_RAW: '/medical/raw',
    MEDICAL_DRINKS: '/medical/drinks',

    NATIONAL_APPETIZERS: '/national/appetizers',
    NATIONAL_FIRST_COURSES: '/national/first-courses',
    NATIONAL_MAIN_COURSES: '/national/main-courses',
    NATIONAL_SIDES: '/national/sides',
    NATIONAL_DESSERTS: '/national/desserts',
    NATIONAL_BAKING: '/national/baking',
    NATIONAL_RAW: '/national/raw',
    NATIONAL_DRINKS: '/national/drinks',

    SAUCES_APPETIZERS: '/sauces/appetizers',
    SAUCES_FIRST_COURSES: '/sauces/first-courses',
    SAUCES_MAIN_COURSES: '/sauces/main-courses',
    SAUCES_SIDES: '/sauces/sides',
    SAUCES_DESSERTS: '/sauces/desserts',
    SAUCES_BAKING: '/sauces/baking',
    SAUCES_RAW: '/sauces/raw',
    SAUCES_DRINKS: '/sauces/drinks',

    DRINKS_APPETIZERS: '/drinks/appetizers',
    DRINKS_FIRST_COURSES: '/drinks/first-courses',
    DRINKS_MAIN_COURSES: '/drinks/main-courses',
    DRINKS_SIDES: '/drinks/sides',
    DRINKS_DESSERTS: '/drinks/desserts',
    DRINKS_BAKING: '/drinks/baking',
    DRINKS_RAW: '/drinks/raw',
    DRINKS_DRINKS: '/drinks/drinks',

    PRESERVES_APPETIZERS: '/preserves/appetizers',
    PRESERVES_FIRST_COURSES: '/preserves/first-courses',
    PRESERVES_MAIN_COURSES: '/preserves/main-courses',
    PRESERVES_SIDES: '/preserves/sides',
    PRESERVES_DESSERTS: '/preserves/desserts',
    PRESERVES_BAKING: '/preserves/baking',
    PRESERVES_RAW: '/preserves/raw',
    PRESERVES_DRINKS: '/preserves/drinks',
} as const;
